-- 创建角色与权限（演示）
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='sss_app') THEN
    CREATE ROLE sss_app LOGIN PASSWORD 'AppPassWord++';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='sss_ro') THEN
    CREATE ROLE sss_ro LOGIN PASSWORD 'ReadOnlyPassWord++';
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO sss_app, sss_ro;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sss_app;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO sss_ro;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sss_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO sss_ro;